mailhole/urls.py
from django.conf import settings
from django.conf.urls import url
import django.views.static
from django.contrib import admin
import mailhole.views
from mailhole.models import Message

urlpatterns = [
    url(r'^admin/', admin.site.urls),

    url(r'^$', mailhole.views.MailboxList.as_view(), name='mailbox_list'),
    url(r'^log/$', mailhole.views.Log.as_view(), name='log'),
    url(r'^login/$', mailhole.views.LoginView.as_view(), name='login'),
    url(r'^api/submit/$', mailhole.views.Submit.as_view(), name='submit'),
    url(r'^(?P<mailbox>[^/]+)/$',
        mailhole.views.MailboxDetail.as_view(), name='mailbox_detail'),
    url(r'^all/(?P<status>inbox|spam|trash)/$',
        mailhole.views.MessageList.as_view(), name='message_list'),
    url(r'^(?P<mailbox>[^/]+)/(?P<status>inbox|spam|trash)/$',
        mailhole.views.MailboxMessageList.as_view(), name='mailbox_message_list'),
    url(r'^(?P<mailbox>[^/]+)/(?P<pk>\d+)/$',
        mailhole.views.MessageDetail.as_view(), name='message_detail'),
    url(r'^(?P<mailbox>[^/]+)/defaction/$',
        mailhole.views.DefaultActionUpdate.as_view(), name='default_action_update'),
]

if settings.DEBUG:
    # Temporary media (user uploaded static files)
    # serving from dev server
    urlpatterns.append(
        url(r'^uploads/(?P<path>.*)$',
            django.views.static.serve,
            {'document_root': settings.MEDIA_ROOT}))

mailhole/models.py
import re
import email
import logging

import django.core.mail
from django.core.mail import EmailMessage
from django.core.mail.message import MIMEMixin
from django.conf import settings
from django.db import models
from django.db.models import Max
from django.contrib.auth.models import User
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.files.base import ContentFile
from django.utils import html, timezone

from mailhole.utils import html_to_plain, decode_any_header
import mailhole.policy
import email.utils


logger = logging.getLogger('mailhole')


class Mailbox(models.Model):
    '''
    An email user whose emails end up in our app.
    '''

    HOLD = 'hold'
    FORWARD = 'forward'
    ACTION = [
        (HOLD, 'Tilbagehold'),
        (FORWARD, 'Videresend'),
    ]
    KEEP = "keep"
    DELETE = "delete"
    DATA_RETENTION = [
        (KEEP, "Behold"),
        (DELETE, "Slet"),
    ]

    name = models.CharField(max_length=100, null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    readers = models.ManyToManyField(User)
    default_action = models.CharField(max_length=10, choices=ACTION,
                                      default=HOLD)
    data_retention = models.CharField(
        max_length=10, choices=DATA_RETENTION, null=True
    )

    def __str__(self):
        return self.name

    @classmethod
    def get_or_create(cls, orig_rcpt_tos, peer=None):
        '''
        If peer is given and no Mailbox with email exists, readers are added
        based on peer.default_readers.
        '''
        if not isinstance(orig_rcpt_tos, list):
            raise ValueError('orig_rcpt_tos must be a list, not a %r' %
                             (type(orig_rcpt_tos),))
        if not all(r.count('@') == 1 for r in orig_rcpt_tos):
            raise ValueError('Invalid email addresses: %r' % (orig_rcpt_tos,))
        domains = set(domain.lower() for r in orig_rcpt_tos
                      for localpart, domain in [r.split('@')])
        if len(domains) != 1:
            raise ValueError(domains)
        domain, = domains
        try:
            return cls.objects.get(name=domain)
        except cls.DoesNotExist:
            mailbox = cls(name=domain)
            mailbox.clean()
            mailbox.save()
            logger.info('mailbox:%s:%s created by peer:%s:%s',
                        mailbox.pk, mailbox.name, peer and peer.pk, peer)
            if peer is not None:
                for r in peer.default_readers.all():
                    mailbox.readers.add(r)
            return mailbox

    @classmethod
    def owned_by_user(cls, user):
        return cls.objects.filter(readers=user)

    @classmethod
    def visible_to_user(cls, user):
        if user.is_superuser:
            return cls.objects.all()
        else:
            return cls.objects.filter(readers=user)

    def folders(self):
        for key, label in Message.STATUS:
            url = reverse('mailbox_message_list',
                          kwargs=dict(mailbox=self.name, status=key))
            qs = self.message_set.filter(status=key)
            yield key, label, url, qs

    def get_absolute_url(self):
        return reverse('mailbox_detail',
                       kwargs=dict(mailbox=self.name))


class Peer(models.Model):
    '''
    A front-end SMTP server who receives emails for our mailboxes.
    '''
    key = models.CharField(max_length=256)
    default_readers = models.ManyToManyField(User, blank=True)
    slug = models.CharField(max_length=30)

    def __str__(self):
        return self.slug

    @classmethod
    def validate(cls, key):
        try:
            return cls.objects.get(key=key)
        except cls.DoesNotExist:
            raise ValidationError('Invalid peer key')


class FilterRule(models.Model):
    SUBJECT_MATCH = 'subject_match'
    SENDER_MATCH = 'sender_match'
    HEADER_MATCH = 'header_match'

    KIND = [
        (SUBJECT_MATCH, 'Subject regex search'),
        (SENDER_MATCH, 'Sender regex search'),
        (HEADER_MATCH, 'Header regex match'),
    ]

    MARK_SPAM = 'spam'
    FORWARD = 'forward'

    ACTION = [
        (MARK_SPAM, 'Markér som spam'),
        (FORWARD, 'Videresend'),
    ]

    order = models.IntegerField()
    peer = models.ForeignKey(Peer, on_delete=models.CASCADE,
                             blank=True, null=True,
                             help_text='Blank betyder "alle servere"')
    kind = models.CharField(max_length=30, choices=KIND)
    pattern = models.CharField(max_length=200)
    examples = models.TextField(
        help_text='Eksempel-matches, én per linje. Linjer der starter med ' +
                  'udråbstegn (!) er negative eksempler. Kommentarer ' +
                  'starter med hegn (#).')
    action = models.CharField(max_length=30, choices=ACTION)

    created_by = models.ForeignKey(User, on_delete=models.SET_NULL,
                                   blank=False, null=True)
    created_time = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return '%s (%s)' % (self.pattern, self.get_kind_display())

    class Meta:
        ordering = ['order']

    def clean(self):
        if self.pattern:
            try:
                re.compile(self.pattern)
            except re.error as exn:
                raise ValidationError('Ugyldig pattern: %s' % (exn,))
            failed = []
            for line in self.examples.splitlines():
                if not line or line.startswith('#'):
                    continue
                if line.startswith('!'):
                    example = line[1:]
                    expect = False
                else:
                    example = line
                    expect = True
                got = self.match_string(example)
                if got is not expect:
                    failed.append(line)
            if failed:
                raise ValidationError('Eksempel fejlede: %r' % (failed,))

    @classmethod
    def filter_message(cls, filters, message):
        '''
        messages is a Message object. filters is a sequence of FilterRules.

        Returns the first filter that matches, if any.

        Filters are applied in the order given and stops at first match.
        '''
        sender = message.orig_mail_from
        headers = message.parsed_headers
        subject = headers.get('Subject') or ''
        header_strs = ['%s: %s' % (k, decode_any_header(v))
                       for k, v in headers.items()]
        for filter in filters:
            if filter._match_message(sender, subject, header_strs):
                return filter

    def _match_message(self, sender, subject, header_strs):
        if self.kind == FilterRule.SUBJECT_MATCH:
            return self.match_string(subject)
        elif self.kind == FilterRule.SENDER_MATCH:
            return self.match_string(sender)
        elif self.kind == FilterRule.HEADER_MATCH:
            return any(map(self.match_string, header_strs))
        else:
            raise Exception(self.kind)

    def match_string(self, text):
        return bool(re.search(self.pattern, text, re.I))

    @classmethod
    def whitelist_from(cls, message, user):
        max_order = cls.objects.all().aggregate(order=Max('order'))['order']
        if max_order is None:
            # No objects exist yet
            max_order = 0
        order = max_order + 1
        from_ = message.from_()
        filter = cls(order=order,
                     kind=FilterRule.HEADER_MATCH,
                     pattern='^From: %s$' % re.escape(from_),
                     examples='From: %s' % (from_,),
                     action=FilterRule.FORWARD,
                     created_by=user)
        test = FilterRule.filter_message([filter], message)
        if test is None:
            raise Exception('FilterRule.filter_message failed')
        filter.save()
        logger.info('user:%s (%s) filter:%s whitelisted %r',
                    user.pk, user.username, filter.pk, from_)


class DjangoMessage(MIMEMixin, email.message.Message):
    pass


def message_upload_to(message: 'Message', filename, suffix=''):
    return 'messages/{peer}/{mailbox}/{now}{suffix}.mail'.format(
        peer=message.peer.slug,
        mailbox=message.mailbox.name,
        now=timezone.now().isoformat().replace(':', '_'),
        suffix=suffix,
    )


def orig_message_upload_to(message: 'Message', filename):
    return message_upload_to(message, filename, '_orig')


class Message(models.Model):
    '''
    A message received by a Peer for one of our mailboxes.
    '''
    RECIPIENT_SEP = ','

    INBOX = 'inbox'
    SPAM = 'spam'
    TRASH = 'trash'

    STATUS = [
        (INBOX, 'Indbakke'),
        (SPAM, 'Spam'),
        (TRASH, 'Slettet'),
    ]
    mailbox = models.ForeignKey(Mailbox, on_delete=models.CASCADE)
    peer = models.ForeignKey(Peer, on_delete=models.CASCADE)
    # RFC 5321 §4.5.3.1.3 Max sender/recipient length is 256 octets
    mail_from = models.CharField(max_length=256)
    rcpt_tos = models.TextField(blank=False)
    orig_mail_from = models.CharField(max_length=256,
                                      blank=False, null=True)
    orig_rcpt_tos = models.TextField(blank=False, null=True)
    message_file = models.FileField(upload_to=message_upload_to)
    orig_message_file = models.FileField(upload_to=orig_message_upload_to,
                                         blank=False, null=True)
    headers = models.TextField(help_text="From orig_message_file")
    outgoing_headers = models.TextField(help_text="From message_file")
    # Unfortunately, MySQL makes it difficult to index more than 190 bytes :-(
    message_id = models.CharField(max_length=190, db_index=True, blank=True, null=True)
    body_text_bytes = models.BinaryField(null=True)
    created_time = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=10, choices=STATUS,
                              default=INBOX)

mailhole/forms.py
import json
import logging

from django import forms
from django.conf import settings
from django.contrib.auth import forms as auth_forms

from mailhole.models import (
    Peer, Message, SentMessage, FilterRule,
)


logger = logging.getLogger('mailhole')


class AuthenticationForm(auth_forms.AuthenticationForm):
    def confirm_login_allowed(self, user):
        super().confirm_login_allowed(user)
        if not user.mailbox_set.exists() and not user.is_superuser:
            raise forms.ValidationError(
                'Du har ingen registrerede emailadresser. ' +
                'Kontakt %s' % settings.MANAGER_NAME)


def split_by_domain(rcpt_tos):
    '''
    Given a list of email addresses, return list of lists,
    each list containing email addresses for a single domain.

    >>> split_by_domain(['a@foo', 'b@foo', 'c@bar'])
    [['c@bar'], ['a@foo', 'b@foo']]
    '''
    by_domain = {}
    for r in rcpt_tos:
        try:
            local, domain = r.split('@')
        except ValueError:
            raise ValueError(r)
        by_domain.setdefault(domain.lower(), []).append(r)
    # List of lists
    return [by_domain[k] for k in sorted(by_domain)]


class SubmitForm(forms.Form):
    key = forms.CharField()
    mail_from = forms.CharField()
    rcpt_tos = forms.CharField()
    message_bytes = forms.FileField()
    orig_mail_from = forms.CharField()
    orig_rcpt_tos = forms.CharField()
    orig_message_bytes = forms.FileField()

    def _clean_rcpt_tos(self, v):
        try:
            rcpt_tos = json.loads(v)
        except ValueError:
            raise forms.ValidationError('Invalid JSON')
        if not isinstance(rcpt_tos, list):
            raise forms.ValidationError('JSON is not a list')
        if not all(isinstance(r, str) for r in rcpt_tos):
            raise forms.ValidationError('JSON is not a list of strs')
        if any(Message.RECIPIENT_SEP in r for r in rcpt_tos):
            raise forms.ValidationError('Recipient must not contain %r' %
                                        (Message.RECIPIENT_SEP,))
        return rcpt_tos

    def clean_rcpt_tos(self):
        return self._clean_rcpt_tos(self.cleaned_data['rcpt_tos'])

    def clean_orig_rcpt_tos(self):
        return self._clean_rcpt_tos(self.cleaned_data['orig_rcpt_tos'])

    def clean(self):
        key = self.cleaned_data.pop('key')
        self.cleaned_data['peer'] = Peer.validate(key)

    def save(self):
        self.cleaned_data['message_bytes'].open('rb')
        message_bytes = self.cleaned_data['message_bytes'].read()
        self.cleaned_data['orig_message_bytes'].open('rb')
        orig_message_bytes = self.cleaned_data['orig_message_bytes'].read()
        split_orig_rcpt_tos = split_by_domain(
            self.cleaned_data['orig_rcpt_tos'])
        messages = []
        for orig_rcpt_tos in split_orig_rcpt_tos:
            messages.append(Message.create(
                peer=self.cleaned_data['peer'],
                mail_from=self.cleaned_data['mail_from'],
                rcpt_tos=self.cleaned_data['rcpt_tos'],
                message_bytes=message_bytes,
                orig_mail_from=self.cleaned_data['orig_mail_from'],
                orig_rcpt_tos=orig_rcpt_tos,
                orig_message_bytes=orig_message_bytes,
            ))
        return messages


class MessageListForm(forms.Form):
    def __init__(self, **kwargs):
        self.messages = list(kwargs.pop('queryset'))
        self.no_outgoing_emails = kwargs.pop("no_outgoing_emails", False)
        super().__init__(**kwargs)

        for message in self.messages:
            spam_k = 'spam_%s' % message.pk
            forward_k = 'forward_%s' % message.pk
            whitelist_k = 'whitelist_%s' % message.pk
            trash_k = 'trash_%s' % message.pk
            self.fields[spam_k] = forms.BooleanField(required=False)
            self.fields[forward_k] = forms.BooleanField(required=False)
            self.fields[whitelist_k] = forms.BooleanField(required=False)
            self.fields[trash_k] = forms.BooleanField(required=False)
            message.form = dict(
                spam=self[spam_k],
                forward=self[forward_k],
                whitelist=self[whitelist_k],
                trash=self[trash_k],
            )

    def clean(self):
        by_pk = {}
        for k, v in self.cleaned_data.items():
            if not v:
                continue
            try:
                mode, pk = k.split('_')
                pk = int(pk)
            except ValueError:
                continue
            if by_pk.setdefault(pk, mode) != mode:
                raise forms.ValidationError(
                    'Du må ikke markere mere end én boks ved en mail ' +
                    '(%s %s %s)' % (pk, by_pk[pk], mode))
            if self.no_outgoing_emails and mode == "forward":
                raise forms.ValidationError(
                    "NO_OUTGOING_EMAIL er i brug"
                )

    def save(self, user):
        for message in self.messages:
            spam_k = 'spam_%s' % message.pk
            forward_k = 'forward_%s' % message.pk
            whitelist_k = 'whitelist_%s' % message.pk
            trash_k = 'trash_%s' % message.pk
            if self.cleaned_data[spam_k]:
                logger.info('user:%s (%s) message:%s marked spam',
                            user.pk, user.username, message.pk)
                message.set_status(Message.SPAM, user=user)
                message.save()
            if self.cleaned_data[trash_k]:
                logger.info('user:%s (%s) message:%s marked trash',
                            user.pk, user.username, message.pk)
                message.set_status(Message.TRASH, user=user)
                message.save()
            if self.cleaned_data[forward_k] or self.cleaned_data[whitelist_k]:
                # SentMessage.create_and_send logs the action
                SentMessage.create_and_send(message=message, user=user)
                message.set_status(Message.TRASH, user=user)
                message.save()
            if self.cleaned_data[whitelist_k]:
                # FilterRule.whitelist_from logs the action
                FilterRule.whitelist_from(message, user)


class MessageDetailForm(forms.Form):
    recipient = forms.EmailField(label='Modtager')
    send = forms.BooleanField(required=False)
    trash = forms.BooleanField(required=False)
    spam = forms.BooleanField(required=False)

mailhole/templates/mailhole/base.html
{% load staticfiles repeatedblocks %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block fulltitle %}{% repeated_block title %}{% endblock %} - {{ SITE_NAME }}{% endblock %}</title>
<!--
<meta name="viewport"
content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1" />
-->
<meta name="referrer" content="origin" />
<link rel="stylesheet" type="text/css" href="{% static 'mailhole/style.css' %}" />
{% block head %}{% endblock %}
</head>
<body>
<nav role="navigation">
<a href="/">{{ SITE_NAME }}</a>
{% block nav %}{% endblock %}
{% block navcurrent %}<span>{% repeat title %}</span>{% endblock %}
</nav>
<main role="main">{% block content %}{% endblock %}</main>
</body>
</html>

mailhole/templates/mailhole/default_action_update.html
{% extends 'mailhole/base.html' %}
{% block title %}Automatisk videresendelse{% endblock %}
{% block content %}
<h1>Automatisk videresendelse for {{ mailbox }}</h1>
<p>
Her kan du vælge om indkomne emails til {{ mailbox }}
skal tilbageholdes for at blive gennemlæst
eller automatisk videresendes.
</p>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Gem" />
</form>
{% endblock %}

mailhole/templates/mailhole/login.html
{% extends 'mailhole/base.html' %}
{% block title %}Log ind{% endblock %}
{% block content %}
<h1>Log ind</h1>
<p>Velkommen til {{ SITE_NAME }}. Hvis du har glemt dit login, så kontakt {{ MANAGER_NAME }}.</p>
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Log ind" />
</form>
{% endblock %}

mailhole/templates/mailhole/mailbox_detail.html
{% extends 'mailhole/base.html' %}
{% block title %}{{ mailbox }}{% endblock %}
{% block content %}
<h1>{{ mailbox }}</h1>
<ul>
    {% for key, label, url, qs in mailbox.folders %}
    <li><a href="{{ url }}">{{ label }}</a> ({{ qs.count }})</li>
    {% endfor %}
</ul>
{% endblock %}

mailhole/templates/mailhole/mailbox_list.html
{% extends 'mailhole/base.html' %}
{% block title %}Modtager-adresser{% endblock %}
{% block content %}
<h1>Modtager-adresser</h1>
{% if user.is_superuser %}
<p><a href="{% url 'log' %}">Log</a></p>
{% endif %}
<ul>
    <li>Alle
        <ul>
            {% for key, label, url, qs in all_folders %}
            <li><a href="{{ url }}">{{ label }}</a> ({{ qs.count }})</li>
            {% endfor %}
        </ul>
    </li>
    {% for mailbox in object_list %}
    <li>{{ mailbox }}
        (<a href="{% url 'default_action_update' mailbox=mailbox.name %}">{{ mailbox.get_default_action_display }}</a>)
        <ul>
            {% for key, label, url, qs in mailbox.folders %}
            <li><a href="{{ url }}">{{ label }}</a> ({{ qs.count }})</li>
            {% endfor %}
        </ul>
    </li>
    {% endfor %}
</ul>
{% endblock %}

mailhole/templates/mailhole/message_detail.html
{% extends 'mailhole/base.html' %}
{% block title %}{{ message.subject|default:BLANK_SUBJECT }}{% endblock %}
{% block nav %}
<a href="{% url 'mailbox_detail' mailbox=message.mailbox.name %}">
    {{ message.mailbox }}</a>
<a href="{% url 'mailbox_message_list' mailbox=message.mailbox.name status=message.status %}">
    {{ message.get_status_display }}</a>
{% endblock %}
{% block content %}
<h1>{{ message.subject|default:BLANK_SUBJECT }}</h1>
<form method="post">{% csrf_token %}
{{ form.errors }}
<p><i>Oprindelig fra:</i> {{ message.from_ }}</p>
<p><i>Fra:</i> {{ message.outgoing_from }}</p>
<p><i>Til:</i> {{ message.to_as_html }} &rarr; {{ message.rcpt_tos }}</p>
<p><i>Sendt:</i> {{ message.parsed_headers.date }}</p>
<p><i>Modtaget:</i> {{ message.created_time }}</p>
{% if message.unsubscribe_links %}
<p><i>List-Unsubscribe:</i> {{ message.unsubscribe_links }}</p>
{% endif %}
{% if message.status_on %}
<p><i>Håndteret:</i> {{ message.status_on }} markeret {{ message.get_status_display }}</p>
{% endif %}
{% if message.status_by %}
<p><i>Håndteret af</i> {{ message.status_by }}</p>
{% endif %}
{% if message.filtered_by %}
<p><i>Håndteret af filter</i> {{ message.filtered_by }}</p>
{% endif %}
<div style="white-space: pre-wrap">{{ message.body_text }}</div>
{% if message.headers %}
<p>{{ form.recipient }} <input type="submit" name="send" value="Videresend" /></p>
<p><input type="submit" name="trash" value="Slet" /></p>
<p><input type="submit" name="spam" value="Markér som spam" /></p>
{% endif %}
</form>
{% endblock %}

mailhole/templates/mailhole/message_list.html
{% extends 'mailhole/base.html' %}
{% block title %}{{ status }} - {{ mailbox }}{% endblock %}
{% block nav %}
{% if all %}<a href="{% url 'mailbox_list' %}">Alle</a>
{% else %}<a href="{{ mailbox.get_absolute_url }}">{{ mailbox }}</a>
{% endif %}{% endblock %}
{% block navcurrent %}<span>{{ status }}</span>{% endblock %}
{% block head %}
<style>
.subject > a {
    display: inline-block;
    max-width: 300px;
    overflow: hidden;
    text-overflow: ellipsis;
    white-space: nowrap;
    vertical-align: top;
}
.received-time { white-space: nowrap; }
</style>
{% endblock %}
{% block content %}
{% if all %}
<h1>{{ status }}</h1>
{% else %}
<h1>{{ mailbox }}</h1>
<h2>{{ status }}</h2>
{% endif %}
{% if inbox %}
<p>
Markér emails som <b>Spam</b> for at sende dem til spammappen,
eller markér <b>Send</b> for at videresende dem til
{% if all %}den rette modtager{% else %}{{ mailbox.email }}{% endif %} og slette dem,
eller markér <b>Slet</b> hvis du bare vil slette dem.
</p>
<p>Markér <b>Send altid</b> for at videresende og oprette en regel.</p>
<p>
<b>Du må ikke videresende spam-mails!</b>
Hvis du er i tvivl, så læs mailen inden du videresender den.
</p>
{% endif %}

<p>
Viser email
{{ page.start_index }}-{{ page.end_index }}/{{ paginator.count }}.
Side:
{% for p in paginator.page_range %}
{% if p == page.number %}
<b>{{ p }}</b>
{% else %}
<a href="?p={{ p }}">{{ p }}</a>
{% endif %}
{% endfor %}
</p>

<form method="post">{% csrf_token %}
{{ form.errors }}
<table>
<thead>
<tr>
{% if inbox %}
<th>Spam</th>
<th>Send</th>
<th>Send altid</th>
<th>Slet</th>
{% endif %}
<th>Fra</th>
<th>Til</th>
<th>Emne</th>
<th>Modtaget</th>
</tr>
</thead>
<tbody>
{% for message in object_list %}
<tr>
    {% if inbox %}
    <td class="spam">{{ message.form.spam }}</td>
    <td class="forward">{{ message.form.forward }}</td>
    <td class="whitelist">{{ message.form.whitelist }}</td>
    <td class="trash">{{ message.form.trash }}</td>
    {% endif %}
    <td class="from">{{ message.from_ }}</td>
    <td class="to">{% if all %}{{ message.mailbox }}
        {% else %}{{ message.to_as_html }}{% endif %}</td>
    <td class="subject"><a href="{{ message.get_absolute_url }}">{{ message.subject|default:BLANK_SUBJECT }}</a></td>
    <td class="received-time">{{ message.created_time }}</td>
</tr>
{% endfor %}
</tbody>
</table>
{% if inbox %}<input type="submit" value="Udfør handlinger" />{% endif %}
</form>
{% endblock %}